Nosto/nosto-magento2-cmp

- Helper/CategorySorting.php
- Helper/Data.php
- Model/Config/Frontend/CategorySorting.php
- Model/Config/Source/CategorySorting.php
- Model/Service/Recommendation/Category.php
- Plugin/Catalog/Block/Toolbar.php
- Plugin/Catalog/Model/Config.php
- Plugin/Catalog/Model/Sortby.php
- etc/adminhtml/system.xml
- etc/config.xml
- etc/di.xml
- etc/module.xml
- registration.php
- view/frontend/layout/default.xml
Implement category personalisation logic. 
closes #1
Category personalisation logic will be migrated from main `nosto-magento2` module to this new one.
Tested locally
ToDo
> Migrate CMP logic from main module.

- Plugin/Catalog/Block/Toolbar.php
- composer.json
- registration.php
Show only products that come from Nosto. 
closes #3
> Fetch only CMP products

- i18n/en_US.csv
Add translation files that the merchant can override if there's a need for modifying texts etc.
> Add translation files

- Observer/App/Action/Action.php
- Utils/Debug/Product.php
- Utils/Debug/ServerTiming.php
Small refactoring & fixing http header values
> Remove extra commas from headers and use constants for header names

- Model/Service/Recommendation/Category.php
- Plugin/Catalog/Block/AbstractBlock.php
- Plugin/Catalog/Block/DefaultParameterResolver.php
- Plugin/Catalog/Block/Pager.php
- Plugin/Catalog/Block/ParameterResolverInterface.php
- Plugin/Catalog/Block/Toolbar.php
- etc/di.xml
> Implement pagination for CMP 

- etc/adminhtml/system.xml
- etc/di.xml
Rename `Category Personalisation` to `Category Merchandising and Personalisation`
closes  #19
> Rename feature name in conifg ui & use preference for di

- Plugin/Catalog/Block/Toolbar.php
> Update CategoryStringBuilder namespace

- Helper/CategorySorting.php
- Plugin/Catalog/Model/Sortby.php
- README.md
- composer.json
- etc/adminhtml/system.xml
- i18n/en_US.csv
Update the terminology used for category merchandising in the module.
> Naming update 

- composer.json
- composer.lock
> Update module-nostotagging version dependency

- CHANGELOG.md
- Model/Service/Recommendation/Category.php
- Plugin/Catalog/Block/Toolbar.php
- Plugin/Catalog/Model/Product.php
- Utils/Debug/ServerTiming.php
- composer.json
- composer.lock
- etc/module.xml
Polish logging and exception handling . 
Method `getCmpResult()` returns only instance of `CategoryMerchandisingResult` . 
Easier debugging.
> Refactor logs and debugging

- Block/SegmentMapping.php
- Plugin/Http/Context.php
- view/frontend/templates/category_merchandising.phtml
- view/frontend/web/js/cmp.js
> Feature - minimize cookie content

- Block/SortOrder.php
- composer.json
- composer.lock
- view/frontend/layout/catalog_category_view.xml
- view/frontend/layout/default.xml
Add sort order tagging to the category pages. 
#39 
This is needed for the CMP tracking
Tested locally
> Add sort order tagging

- Block/Meta.php
- Block/SegmentMapping.php
- Helper/Data.php
- view/frontend/layout/default.xml
- view/frontend/templates/meta.phtml
Add module version to the meta tagging.
#41 
It helps in debugging.
Tested locally
> Add Nosto CMP module version to the meta tags

- Plugin/Catalog/Model/Product.php
Add an overridable URL fragment
Closes #44
See issue
Open any category page with CMP enabled and check the parameter at the end of the URL
N/A
> Add #nosto_cmp url fragment

- Block/CategoryMapping.php
- Plugin/Catalog/Helper/Category.php
- phan.php
- view/frontend/templates/category_mapping.phtml
Pass the exception object to the logger
> Fix exception handling

- .github/workflows/phan.yml
- Plugin/Catalog/Model/Sortby.php
- composer.json
- composer.lock
There's a mismatch in the dependencies between this module and the main tagging module. Fix by updating the semantic versioning of the php-sdk dependency version.
> Hotfix/1.2.2 - Fix SDK versioning

- .github/workflows/action.yml
Add all other packages to install as a CI step in order to prevent version constraint related errors
> Add MSI, Nostotagging and ITP modules to project deps step

- Block/CategoryMapping.php
- Helper/Data.php
- etc/adminhtml/system.xml
- etc/config.xml
> Add flag to map all categories in the script 

- CHANGELOG.md
- composer.json
- etc/module.xml
> Update change log & bump version

- CHANGELOG.md
- Helper/Data.php
- Model/Service/Recommendation/Category.php
- Model/Service/Recommendation/StateAwareCategoryService.php
- Plugin/Catalog/Block/Toolbar.php
- etc/adminhtml/system.xml
- etc/config.xml
*PLEASE NOTE* This should not be merged prior to https://github.com/Nosto/nosto-magento2-cmp/pull/71
Implement support for using max product limit in 3.X version as well.
Tested locally with both Graphql and store front.
> Implement support for max limit for 3.X

- Model/Service/Recommendation/BatchModel.php
- Model/Service/Recommendation/BatchModelInterface.php
- Model/Service/Recommendation/Category.php
- Model/Service/Recommendation/CmpSession.php
- Model/Service/Recommendation/StateAwareCategoryService.php
- Observer/App/Action/PostRequestAction.php
- Observer/App/Action/PreRequestAction.php
- Utils/CategoryMerchandising.php
- composer.json
- composer.lock
- etc/events.xml
Add the batch token to the graphql query. The token will be stored in the session when the request is done, and it will be picked for the next page query.
> Store BatchToken in session

- CHANGELOG.md
- composer.json
- etc/module.xml
> Release - 3.1.0-rc1

- Exception/CmpException.php
- Model/Service/Recommendation/GraphQlParamModel.php
- Model/Service/Recommendation/SessionService.php
- Observer/App/Action/PostRequestAction.php
- Observer/App/Action/PreRequestAction.php
- Plugin/CatalogGraphQl/Products/Query/Search.php
- Plugin/Framework/Search/Request/AbstractHandler.php
- Plugin/Framework/Search/Request/GraphQlHandler.php
- Plugin/Framework/Search/Request/WebHandler.php
- composer.json
- composer.lock
- phan.php
Pagination is broken for M2 graphql products query. The total number of pages is always one as a result of cmp results. Added a interceptor and calculated the total number of pages based on our results.
> Fix graphql pagination

- CHANGELOG.md
- composer.json
- etc/module.xml
> Release 3.1.0-rc2

- CHANGELOG.md
- Model/Filter/WebFilters.php
- Plugin/Catalog/Block/Toolbar.php
- composer.json
- etc/module.xml
Build filters when MySQL is used as a search engine.
> ADS-2847: Fix filters for toolbar plugin

- .github/workflows/action.yml
- .github/workflows/ide.yml
- .github/workflows/phan.yml
- CHANGELOG.md
- composer.json
- composer.lock
- etc/module.xml
- view/frontend/layout/catalog_category_view.xml
- view/frontend/layout/default.xml
Category maps and some other layout blocks are rendered when the CM is set to disabled. Stop them from rendering by using `ifconfig` attribute.
> Render layouts only when CM configuration is enabled

- .github/workflows/action.yml
- .github/workflows/ide.yml
- .github/workflows/phan.yml
- CHANGELOG.md
- composer.json
- etc/module.xml
- view/frontend/layout/default.xml
Cache category mapping block and set cache lifetime to one day. It brings performance improvements. The block is generated once and it's cached for every other page.
> Release/3.1.0 rc7 - Cache category mapping block

- CHANGELOG.md
- Model/Filter/WebFilters.php
- composer.json
- etc/module.xml
Boolean filters are ignored when building the CMP query
> Build boolean filters

- CHANGELOG.md
- composer.json
- etc/acl.xml
- etc/adminhtml/system.xml
- etc/module.xml
`acl.xml` file is missing from the module. Add the file.
> Hotfix 3.2.2 - Add acl configuration file

- CHANGELOG.md
- composer.json
- etc/module.xml
Release candidate nr 1 for `3.3.0`
> Release 3.3.0-rc1

- CHANGELOG.md
- composer.json
- etc/module.xml
> Release 3.3.0-rc2

- CHANGELOG.md
- composer.json
- etc/module.xml
> Release 3.3.0-rc3

- Plugin/Framework/Search/Request/AbstractHandler.php
- Plugin/Framework/Search/Request/GraphQlHandler.php
- Plugin/Framework/Search/Request/WebHandler.php
- etc/di.xml
Add pageSize limit for requests
> Add pageSize limit for requests

- CHANGELOG.md
- composer.json
- etc/module.xml
> Release 3.3.0-rc7

- Plugin/Catalog/Block/Toolbar.php
- etc/di.xml
Add page size limit through DI in Toolbar. See https://github.com/Nosto/nosto-magento2-cmp/pull/119 for more info
Improved exception handling and logging in other classes of the module to ease the debug process with the merchant.
https://github.com/Nosto/nosto-magento2-cmp/issues/118
Allow merchant to add custom page size limit for the CM
Local M2 instance
N/A
> Add page size limit through DI for Toolbar

- Block/CategoryMapping.php
- CHANGELOG.md
- Helper/Data.php
- Model/Service/Facet/BuildWebFacetService.php
- Model/Service/Recommendation/StateAwareCategoryService.php
- Plugin/Catalog/Block/AbstractBlock.php
- Plugin/Catalog/Block/Pager.php
- Plugin/Catalog/Block/Toolbar.php
- Plugin/Catalog/Model/Config.php
- Plugin/Framework/Search/Request/AbstractHandler.php
- Plugin/Framework/Search/Request/GraphQlHandler.php
- Plugin/Framework/Search/Request/WebHandler.php
`StoreManagerInterface` usage is removed from the module and replaced with a `Nosto\Tagging\Helper\Scope` helper. Updated all methods and return types. Removed instance checks and phan escapes.
Closes #101 
Reduce direct usage of StoreManagerInterface.
Locally
> Remove StoreManagerInterface and use helper from Nosto_Tagging module instead

- CHANGELOG.md
- Model/Service/Facet/BuildWebFacetService.php
- composer.json
- composer.lock
- etc/module.xml
Price is represented as string, meanwhile in our graphql is declared as float.
> Release 3.3.0-rc8 / Cast price filters to float

- Block/CategoryMapping.php
- Exception/JsonEncodeFailureException.php
- Model/Cache/Type/CategoryMapping.php
- Model/Service/Category/CachingCategoryMappingService.php
- Model/Service/Category/CategoryMappingService.php
- Model/Service/Category/CategoryMappingServiceInterface.php
- etc/cache.xml
- etc/di.xml
- view/frontend/templates/category_mapping.phtml
Store category mapping json data into the cache using the magento framework cache interface. 
closes #126
> Cache category mapping json

- CHANGELOG.md
- Plugin/CatalogGraphQl/Products/Query/Search.php
- composer.json
- etc/module.xml
Reverts Nosto/nosto-magento2-cmp#148
> Revert "Add fallback sorting for GraphQL"

- Model/Service/Merchandise/RequestParamsService.php
The issue arises when a customer reloads or executes the query for the same page many times. After the first call the module stores the batch token, and will use it for the next call. But unintentionally this creates a bug when reloading the page. The token will point to the next page in Nosto, meanwhile Magento is requesting results for the same page. 
Solved by using the batchModel only when requested page is greater by 1 than the previously requested page.
The issue should be fixed in the Magento module, check if the limit used is the same with the Model saved in the session.
Bug
GraphQl, Postman
> CM pagination issue when reloading same page

- .github/workflows/action.yml
- Block/Compatibility.php
- CHANGELOG.md
- Model/System/Message/Notification/CmpIncompatible.php
- composer.json
- etc/adminhtml/di.xml
- etc/module.xml
- view/frontend/layout/default.xml
- view/frontend/templates/compatibility.phtml
Add CMP compatibility meta tag. Alternative solution for #157
> Add CMP compatibility meta tag

- CHANGELOG.md
- composer.json
- composer.lock
- etc/module.xml
> Update nosto/module-nostotagging to ^7.0.0

- CHANGELOG.md
- Plugin/Framework/Search/Search.php
- composer.json
- etc/di.xml
- etc/module.xml
https://github.com/Nosto/wiki-docs/pull/95
> Release 5.2.2 - Revert "Fix counter total products rendered"

- Plugin/Api/Search/SearchResultApplier.php
- etc/di.xml
> Improve compatibility with Magento 2.4.6

- CHANGELOG.md
- Plugin/Api/Search/SearchResultApplier.php
- composer.json
- etc/di.xml
- etc/module.xml
> Release 5.3.0
