Model/Service/Recommendation/Category.php
Plugin/Catalog/Block/Toolbar.php
Plugin/Catalog/Model/Product.php

* Add hard limit of 100 products for graphql queries
* Use Magento's collection size as limit for CMP operation  
* Add additional tracking parameters to the product URLs

Fix result limits add additional tracking parameters to product URLs

---

Plugin/Catalog/Block/AbstractBlock.php
Plugin/Catalog/Block/DefaultParameterResolver.php

1 - Noticed that too many calls are made to get the current order so it's value will be stored in a static variable
2 - Fix bug when calling method on null
closes #21 , #20

Reduce the number of calls to getCurrentOrder method

---

Plugin/Catalog/Block/Toolbar.php

After trying to integrate with another module, noticed that `Product\Collection` is used instead of `Fulltext\Collection`. This way the module was crashing. 
closes #29

Replace FulltextCollection with ProductCollection

---

Block/CategoryMapping.php

The current implementation does not take into account url rewrites, as a result the category string from the mapping would not match exactly the category string on the navigation bar. Instead, use the native `getUrl()` method from the category model.

Build correct category url

---

CHANGELOG.md
Plugin/Catalog/Model/Sortby.php
composer.json
etc/module.xml

Fix array to string conversion for the Nosto sorting option in the admin catalog page
closes #55

Hotfix/1.2.1 - Fix array to string conversion in Sortby plugin

---

CHANGELOG.md
Helper/Data.php
Plugin/Catalog/Block/Toolbar.php
composer.json
etc/adminhtml/system.xml
etc/config.xml
etc/module.xml

Introduce possibility to define max products to be fetched from Nosto.
#72
This is needed for category pages that allow all products to be viewed on a category page.  
Tested locally with several different max limits.

Introduce possibility to define max products to be fetched from Nosto

---

CHANGELOG.md
composer.json
etc/config.xml
etc/module.xml

Fix getting the default max product limit for CMP graphql calls and set the default limit to be 250 which is the max limit on Nosto's end. 
Pagination is broken if max product limit is not set.  
Tested locally

Hotfix 2.0.3 - fix max product limit

---

Model/Service/Recommendation/Category.php
composer.json
composer.lock

Change the module to use batched CMP operations in order to get around the limit of max 250 products returned by graphql API. 
#78 
In some cases we need to fetch more than 250 products from Nosto.
Tested locally

Bump SDK version & change the module to use batched CMP operation

---

CHANGELOG.md
Exception/MissingCookieException.php
Model/Service/Recommendation/StateAwareCategoryService.php
Plugin/Catalog/Block/Toolbar.php
Plugin/Framework/Search/Request/AbstractHandler.php
composer.json
etc/module.xml

In case the customer refuses personalisation cookies,  the module will make CMP calls with null customerId

Check customerId is not null for fetching CMP results

---

.github/workflows/action.yml
.github/workflows/ide.yml
.github/workflows/phan.yml
CHANGELOG.md
composer.json
composer.lock
etc/module.xml

Installing the module through `composer require nosto/module-nostotagging-cmp:@stable` will install 3.0.0 instead of the latest 3.1.0. This happens because the declared module version in composer file was set to 3.1.0-rc7 which lead to packaigist not recognizing the latest release 3.1.0. Fix the version as a hotfix, the composer will install the latest version.

Fix version and update changelog

---

Block/Meta.php
CHANGELOG.md
Model/Filter/WebFilters.php
composer.json
etc/module.xml
view/frontend/templates/meta.phtml

When the module fails to get the value of a facet/filter, it does not log the filter name, which makes it difficult to debug. 
The name of the filter is added to ease the debugging process.

Hotfix 3.1.2 - Improve logging when building fitlers

---

Helper/Data.php
Model/Config/Source/FallbackSorting.php
Plugin/Framework/Search/Request/AbstractHandler.php
Plugin/Framework/Search/Request/GraphQlHandler.php
Plugin/Framework/Search/Request/WebHandler.php
etc/adminhtml/system.xml
etc/config.xml

Add a fallback sorting option in case no products are returned by Nosto. 
This feature will only be working with Elasticsearch implementation

Add fallback sorting to relevance

---

Plugin/Catalog/Block/AbstractBlock.php
Plugin/Catalog/Block/Pager.php
Plugin/Catalog/Block/Toolbar.php
Plugin/Framework/Search/Search.php
etc/di.xml

Override the SearchResult total count by passing the value returned by Nosto CMP result. A few categories were not being displayed in the filters due to M2 comparing total nr of products of subcategory with the collection total, which in CM case is equal to the page size. 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogSearch/Model/Layer/Filter/Category.php#L136

Set total to SearchResult

---

Model/Service/Recommendation/StateAwareCategoryService.php
Model/Service/Session/SessionService.php
composer.json
composer.lock

The module would fallback on one of the Magento's sorting when the customer identifier was missing. But the result was cached and the same fallback is shown to customer with 2c.cid cookie also.
Fix this scenario by creating a new nosto session through Graphql and use that identifier to fetch results.

Display CM results when customer cookie is missing

---

Plugin/Catalog/Block/Toolbar.php
Plugin/Framework/Search/Request/AbstractHandler.php
Plugin/Framework/Search/Request/RequestCleaner.php
Utils/Search.php

CM code is being executed also on the search page. This is not a desired behaviour, as it does not include a specific category. Added a check to avoid execution in search page for both configurations ES and MySQL

Remove nosto sort option in case of a search page

---

Model/Service/Recommendation/Category.php

In order to make debugging easier in the future, the module should pass the magento and the module version in the GraphQl request headers.
closes #125

Pass platform and module version as user agent

---

composer.json
composer.lock

I was having issues with running `composer` commands locally in the module the fix from [this](https://docs.nosto.com/magento-2/installing#magentos-repo-does-not-contain-the-latest-release) part of the docs helped fixing it. Was thinking if it can be merged
Composer fails locally within the module

Exclude nosto from Magento repo, update lock

---

CHANGELOG.md
Plugin/CatalogGraphQl/Products/DataProvider/ProductSearch.php
composer.json
etc/di.xml
etc/module.xml

The results set which is fetched from ES is sorted again when using Magento's GraphQl as a delivery channel.
Fix this by resorting the products again. 
closes #142

Hotfix 3.3.1 - Fix CM sorting issue for Magento's GraphQl

---

CHANGELOG.md
Plugin/CatalogGraphQl/Products/Query/Search.php
composer.json
etc/module.xml

If you request a category page that does not have CMP enabled with sorting set to `nosto_personalized` the error will be returned stating: 
**"currentPage value %1 specified is greater than the %2 page(s) available."**
This is due to the error in `Magento\CatalogGraphQl\Model\Resolver\Products::61` where `$searchResult->getCurrentPage()` is 1 and $searchResult->getTotalPages() is 0 because Nosto manually sets the total pages value to 0 in the plugin. I have removed the manual overriding of the total pages value and it is now fetched from the searchResult object.
Example of a query:
`{
"query": "{ products( filter: { category_id: { eq: \"12\" } }, currentPage: 1, pageSize: 20 sort: {nosto_personalized: ASC} ) {  items { name } } }"
}`
-
Fix error for CMP on GraphQL for default categories …

Set total page count to searchResult value instead of calculating manually

---

CHANGELOG.md
Plugin/CatalogGraphQl/Products/Query/Search.php
composer.json
etc/module.xml

Fixing issue where fallback sorting set by a merchant is ignored and default position sorting is applied on categories where CMP is disabled.
Add fallback sorting in the search plugin.
Fallback sorting needs to work in GraphQL
Locally

Add fallback sorting for GraphQl

---

CHANGELOG.md
Plugin/CatalogGraphQl/Products/DataProvider/ProductSearch.php
Plugin/CatalogGraphQl/Products/Query/Search.php
composer.json
etc/module.xml

A pagination issue is happening on Magento's GraphQl. For pages bigger than 1 the result set is empty.
The problem relies in `Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\ProductSearch` , a new collection is created and an `OFFSET` equals to the page size is applied to the MySQL query. 
The offset is removed by setting the page size manually to 1 if nosto_personalized sorting is applied.

Hotfix/4.0.1 - Fix CM GraphQl pagination issue

---

.github/workflows/ide.yml
.github/workflows/phan.yml
CHANGELOG.md
Exception/InvalidCategoryTypeException.php
Model/Service/Merchandise/RequestParamsService.php
composer.json
etc/module.xml

Might cause a lot of errors when custom handled categories are not returned:
```
report.CRITICAL: TypeError: Nosto\Tagging\Model\Service\Product\Category\DefaultCategoryService::getCategory(): Argument #1 ($category) must be of type Magento\Catalog\Model\Category, null given, called in /app/{REDACTED}/vendor/nosto/module-nostotagging-cmp/Model/Service/Merchandise/RequestParamsService.php on line 227 and defined in /app/{REDACTED}/vendor/nosto/module-nostotagging/Model/Service/Product/Category/DefaultCategoryService.php:102```

hotfix 5.3.1 - TypeCheck category building string
